name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: macos-latest
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "1"
      PUPPETEER_SKIP_DOWNLOAD: "1"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.2.2

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Audit formula
        run: brew audit --strict Formula/js-recon.rb

      - name: Install formula
        run: brew install --build-from-source Formula/js-recon.rb

      - name: Test formula
        run: brew test Formula/js-recon.rb
