name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "1"
      PUPPETEER_SKIP_DOWNLOAD: "1"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.2.2

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Audit formulas
        run: |
          brew audit --strict shriyanss/tap/js-recon
          brew audit --strict shriyanss/tap/js-recon-alpha
          brew audit --strict shriyanss/tap/js-recon-beta

      - name: Install formulas
        run: |
          brew install --build-from-source shriyanss/tap/js-recon
          brew install --build-from-source shriyanss/tap/js-recon-alpha
          brew install --build-from-source shriyanss/tap/js-recon-beta

      - name: Test formulas
        run: |
          brew test shriyanss/tap/js-recon
          brew test shriyanss/tap/js-recon-alpha
          brew test shriyanss/tap/js-recon-beta
